name: My-first-workflow

on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome message
          run: echo "first workflow"

        - name: list files
          run: ls
          
          